# Site settings
title: Portrait by img.ly
description: Stylized Selfies & Artworks

google_analytics: "-"
addthis_id: "-"

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/imgly
  - title: facebook
    url: https://facebook.com/imgly
  #- title: github
  #  url: http://github.com/jekyll

sass:
  sass_dir: _sass

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
